name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cargo:
    name: Cargo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.96"
          components: clippy,rustfmt

      - name: Check
        run: cargo check --locked

      - name: Clippy
        run: cargo clippy --locked --all-targets --all-features -- -D warnings

      - name: Test
        run: cargo test --locked

  taplo:
    name: Taplo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.96"

      - name: Install taplo
        run: cargo install taplo-cli --locked

      - name: Check TOML formatting
        run: taplo fmt --check

  typos:
    name: Typos
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.96"

      - name: Install typos
        run: cargo install typos-cli --locked

      - name: Check typos
        run: typos
